TasksManager.Exception.RegisterTask=Aufgabe ist "Null" oder Aufgaben-ID {0} ist bereits vorhanden\!
TasksManager.Exception.DeregisterTask=Keine Aufgabe mit ID {0} registriert\!
TasksManager.Excepion.RegisterWizard=ID des Assistenten ist "Null"\!

WizardBase.Excepion.RegisterWizard=ID der Aufgabe {0} ist nicht registriert\!
WizardBase.error.ErrorsEncountered=Aufgetretene Fehler
WizardBase.Next=Weiter >
WizardBase.Back=< Zurück
WizardBase.Finish=&Fertig stellen
WizardBase.Cancel=Abbrechen
WizardBase.error.FollowingErrorsReportedByTask=Das soeben beendete Aufgabenfeld hat folgende Fehler zurückgegeben:
WizardBase.error.FollowingErrorEncountered=Es sind folgende Fehler aufgetreten:
WizardBase.error.FollowingErrorsReportedWhileVerifying=Bei der Überprüfung der Diagrammdefinition wurden folgende Fehler ermittelt:
ErrorDialog.text.ErrorList=Liste der Fehler:
ErrorDialog.text.ShowDetails=Details &anzeigen...
ErrorDialog.text.SuggestedFixes=Vorschläge zur Fehlerbehebung:
ErrorDialog.text.FixIt=\ \ \ &Beheben   
ErrorDialog.text.ProceedWithoutFixing=&Weiter, ohne die Fehler zu beheben
ErrorDialog.text.Exception=Ausnahme:
ErrorDialog.text.ShowTrace=Ablaufverfolgung anzeigen...
ErrorDialog.text.StackTrace=Ablaufverfolgungsstapel:
ErrorDialog.text.Ok=\ \ \ \ \ OK     
ErrorDialog.text.CausedBy=\n\nVerursacht durch:

SubtaskHistory.Tooltip.Back=Zurück zu {0}
SubtaskHistory.Text.Back=Zurück
SubtaskHistory.Tooltip.Forward=Weiter zu {0}
SubtaskHistory.Text.Forward=Weiter
SubtaskHistory.Text.Invalid=\#Ungültig
